name: CI
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: a20erigomvil_mathPotato
          MYSQL_USER: a20erigomvil_Potato   
          MYSQL_PASSWORD: Potato123
        ports:
          - 3306:3306 
    
    steps:
    - name: Checkout Laravel
      uses: actions/checkout@v2

    - name: Cache composer dependencies
      uses: actions/cache@v4
      run: composer install -q --no-interaction --no-suggest --prefer-dist --optimize-autoloader --no-progress --no-scripts
    - name: Generate key
      run: php artisan key:generate
    - env


